### ISSUE TITLE
BUG: deploying kustomizationRefs fails when resources are not ordered correctly

### ISSUE THREAD

**Issue by rbjorklin** [projectsveltos/addon-controller#568] opened 2024-05-29 02:45 UTC
First of all: big thanks for fixing #565! That enabled me to get a bit further!

# Problem Description

My deployment is now failing with the following error:
```
Status:
  Dependencies:  All dependencies deployed
  Feature Summaries:
    Failure Message:    no matches for kind "Alertmanager" in version "monitoring.coreos.com/v1"
    Feature ID:         Kustomize
    Hash:               Xs9cDng9DO19cmZTInB4AqQLVuI+6Z3EYaOd6HF1TUo=
    Last Applied Time:  2024-05-29T01:06:52Z
    Status:             Provisioning
Events:                 <none>
```

This error presents itself as the `Alertmanager` appears before the corresponding CRD in my `kustomization.yaml` file. I managed to work around this by [patching the ksort kubectl plugin](https://github.com/superbrothers/ksort/pull/59) but expecting everyone who uses Kustomize to sort their list of resources seems a bit inconvenient. Is there a way the apply could continue with the next resource in the list allowing the state to eventually reconcile?

# System Information

CLUSTERAPI VERSION: `v1.7.2`
SVELTOS VERSION: `0.31.0`
KUBERNETES VERSION: `1.30.1`

**Comment by gianlucam76** [comment] 2024-05-29 08:44
Thanks @rbjorklin 

That might have unintended consequences. I looked at the helm you started from, and there CRDs are listed before anything else. 

Sveltos essentially tries in the order resources are provided to it and stop when there is an error.

Would you mind closing this and open a discussion on whether we need a "ContinueOnError" field? That would be false by default (so on error Sveltos would stop), but if true Sveltos will continue to next resource.

**Comment by rbjorklin** [comment] 2024-05-29 18:52
Ah. I guess because I split each resource into its own file I have brought this problem onto myself...

My workflow is as follows:
* `helm template` a chart and split the resources into individual files with the [slice](https://github.com/patrickdappollonio/kubectl-slice) plugin.
* Assemble `kustomization.yaml` with `kustomize create --autodetect`

I guess my issue should instead be reported against the `kustomize` project and the sorting happen as a part of the `--autodetect` behaviour.

I'm okay with this outcome however if you still want to continue the conversation I think you as a repo owner can convert a GH issue to a discussion otherwise please just go ahead and close this when you see it.

Thanks for your time @gianlucam76! :heart:

**Comment by gianlucam76** [comment] 2024-05-30 06:53
Thank you. For now I will close this (as it is current expected behaviour) and open a Poll.

**Closed by gianlucam76** 2024-05-30 06:53 UTC
Labels: bug
